basePath: /
definitions:
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:7080
info:
  contact: {}
  description: This is a goparkin back end API.
  title: Goparkin API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user in the database
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a user
      tags:
      - users
swagger: "2.0"
